### ISSUE TITLE
KeyError: 'Price/Coin'

### ISSUE THREAD

**Issue by jamalv** [tnvmadhav/notion-crypto-integration#4]
I purchased this script 2 days ago and had it working quite quickly.

I don't think I have changed anything since, but today I am getting the following error:

```
Traceback (most recent call last):
  File "read.py", line 102, in <module>
    MyIntegration().UpdateIndefinitely()
  File "read.py", line 21, in __init__
    self.getNotionDatabaseEntities()
  File "read.py", line 42, in getNotionDatabaseEntities
    self.my_variables_map["NOTION_ENTRIES"].update({v["properties"]["Name"]["title"][0]["text"]["content"]: {"page": v["id"], "price": float(v["properties"]["Price/Coin"]["number"])}})
KeyError: 'Price/Coin'
```

Did anything break with the integration/API or am I doing something wrong here?

**Comment by tnvmadhav** [comment]
Apologies for the delayed Response. 

The issue might be that, the notion entry for 'Price/Coin' value is `0`

Let me know if that is the case.

**Comment by tnvmadhav** [comment]
I hope the issue has been resolved
Closing this issue
Feel free to reopen if that's not the case 

:)
