### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by KaywanM** [tnvmadhav/notion-crypto-integration#5]
I got the code:

I ran the command: 'py read.py' in step 6 of the setup, and I got this. Is this code broken???

Traceback (most recent call last):
  File "C:\Users\kaywa\OneDrive\Desktop\notion-crypto-integration-main\read.py", line 102, in <module>
    MyIntegration().UpdateIndefinitely()
  File "C:\Users\kaywa\OneDrive\Desktop\notion-crypto-integration-main\read.py", line 20, in __init__
    self.getDatabaseId()
  File "C:\Users\kaywa\OneDrive\Desktop\notion-crypto-integration-main\read.py", line 31, in getDatabaseId
    self.my_variables_map["DATABASE_ID"] = response.json()["results"][1]["id"]
IndexError: list index out of range

**Comment by tnvmadhav** [comment]
Hi,

I Apologize if there is any confusion. However, the code should still work without issues.

The error you're having happens when the notion integration isn't shared with the right database.

Can you share which page you shared the notion integration with?

**Comment by tnvmadhav** [comment]
Hello there, here's a video tutorial I've recorded to show how to get this to work.

https://drive.google.com/file/d/1Rd5NjGDTu-BNWJjTP_Ip3rJMtLpybLwC/view?usp=sharing

Hope this clarifies it all :)

**Comment by tnvmadhav** [comment]
I am closing this as it has [evidently](https://drive.google.com/file/d/1Rd5NjGDTu-BNWJjTP_Ip3rJMtLpybLwC/view) been working. Feel free to reopen if necessary.
